trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@1
  displayName: 'Azure CLI'

  inputs:
    azureSubscription: 'test'
    scriptLocation: inlineScript
    inlineScript: |
      az devops login --org https://dev.azure.com/jaiyeoribe001
      az pipelines variable-group list --organization https://dev.azure.com/jaiyeoribe001 -project "test" --verbose

  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
