# Azure DevOps Pipeline YAML to Install Pre-release Az.DesktopVirtualization Module

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Install Az.DesktopVirtualization Pre-release'
  inputs:
    targetType: 'inline'
    script: |
      Install-PackageProvider -Name NuGet -Force
      Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
      Install-Module -Name Az.DesktopVirtualization -AllowPrerelease -Force -AllowClobber -Scope CurrentUser
      Import-Module Az.DesktopVirtualization
      Write-Host "Az.DesktopVirtualization module installed successfully."

- task: PowerShell@2
  displayName: 'Verify Module Installation'
  inputs:
    targetType: 'inline'
    script: |
      Get-Module -ListAvailable Az.DesktopVirtualization"