trigger:
- main

pool:
  name: 'test-vm'

steps:
- script: |
    git init repo
    cd repo
    git remote add origin https://your-repo-url.com/your-project.git
    git -c http.extraheader="Authorization: Bearer YOUR_HARDCODED_TOKEN_HERE" fetch --verbose --force --tags --progress --no-recurse-submodules origin --depth=1
  displayName: 'Git Fetch with Hardcoded Auth Header'
