trigger:
- main

# Use your self-hosted agent pool
pool:
  name: 'jaiyeoribe-mdp-pool'  # Replace with your actual agent pool name

variables:
  JAVA_DOWNLOAD_URL: 'https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz'
  JAVA_ARCHIVE_NAME: 'jdk-17_linux-x64_bin.tar.gz'
  JAVA_EXTRACTED_DIR: 'jdk-17'

steps:
- script: |
    echo "Downloading Java from $JAVA_DOWNLOAD_URL"
    curl -L -o $JAVA_ARCHIVE_NAME $JAVA_DOWNLOAD_URL
  displayName: 'Download Java'

- script: |
    echo "Browsing google.com"
    curl -I https://www.google.com
  displayName: 'Browse Google.com'

